namespace: redhat
name: wildfly
version: "1.0.0"
readme: README.md
authors:
  - Romain Pelisse <belaran@redhat.com>
  - Andrew Block <ablock@redhat.com>
  - Harsha Cherukuri <hcheruku@redhat.com>
description: This Ansible Collection regroups several playbooks (packaged as role) to help install, setup and maintain Java JEE appserver Wildfly (and its product counterpart [JBoss Enterprise Application (EAP)](https://www.redhat.com/en/technologies/jboss-middleware/application-platform) ) within the configuration management tool Ansible.
license_file: "LICENSE"
tags:
  - java
  - jboss
  - wildfly
  - cli
  - server
dependencies:
  redhat.redhat_csp_download: '>=1.2.0'
repository: https://github.com/ansible-middleware/wildfly_collection
documentation: https://github.com/ansible-middleware/wildfly_collection
homepage: https://github.com/ansible-middleware/wildfly_collection
issues: https://github.com/ansible-middleware/wildfly_collection/issues
