---
wildfly_config_base: standalone-full-ha.xml
wildfly_instances_home: '/opt/instances/'
# Reduce memory for testing to allow multiple instances on one container
wildfly_java_opts: '-Xmx256M -Xms96M -XX:MaxMetaspaceSize=192m'
wildfly_enable_yml_config: True
wildfly_yml_configs:
  - yaml_configuration.yml.j2
  - configure_tcp_ping.yml.j2
