---
- name: Converge
  hosts: all
  vars_files:
    - vars/main.yml
  collections:
    - middleware_automation.jcliff
  roles:
    - wildfly_install
    - wildfly_systemd
  tasks:

    - name: "Install Postresql driver"
      include_role:
        name: wildfly_driver
        tasks_from: jdbc_driver.yml
      vars:
        wildfly_user: wildfly
        jdbc_driver_module_dir: "{{ wildfly.home }}//modules/org/postgresql/main"
        jdbc_driver_version: 9.2-1002-jdbc4
        jdbc_driver_jar_filename: "postgresql-{{ jdbc_driver_version }}.jar"
        jdbc_driver_jar_url: "https://repo.maven.apache.org/maven2/org/postgresql/postgresql/{{ jdbc_driver_version }}/{{ jdbc_driver_jar_filename }}"
        jdbc_driver_jar_installation_path: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"
        jdbc_driver_module_name: "org.postgresql"
