---
- assert:
    that:
      - wildfly is defined
      - wfly_download_url is defined
      - wildfly.home is defined
      - workdir is defined
    quiet: true

- include_tasks: user.yml

- package:
    name: "{{ item }}"
    state: present
  loop:
      - unzip
      - tar
      - java-1.8.0-openjdk

- name: "Ensures workdir {{ workdir }} exists."
  file:
    path: "{{ workdir }}"
    state: directory
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"

- name: "Download and unzip Wildfly zipfile from {{ wfly_download_url }}"
  unarchive:
    src: "{{ wfly_download_url }}"
    dest: "{{ workdir }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    remote_src: yes
    creates: "{{ wildfly.home }}"

- stat:
    path: "{{ wildfly_home }}"
  register: stat_wildfly_home
  when:
    - wildfly_home is defined

- file:
    path: "{{ wildfly_home }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    recurse: yes
  when:
    - stat_wildfly_home is defined
    - stat_wildfly_home.stat is defined
    - stat_wildfly_home.stat.exists
