---
- name: "Start Service {{ instance_name }}"
  include_tasks: service.yml
  vars:
    instance_state: started

- name: "Stop Service {{ instance_name }}"
  include_tasks: service.yml
  vars:
    instance_state: stopped

- name: "Restart Service {{ instance_name }}"
  include_tasks: service.yml
  vars:
    instance_state: restarted
