---
- name: Prepare
  hosts: all
  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Ensure required packages are installed."
      ansible.builtin.yum:
        name:
          - sudo
          - java-1.8.0-openjdk
          - procps-ng
        state: present

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: "Retrieve assets server from env"
      ansible.builtin.set_fact:
        assets_server: "{{ lookup('env','MIDDLEWARE_DOWNLOAD_RELEASE_SERVER_URL') }}"

  tasks:
    - name: "Proceed with installation"
      ansible.builtin.include_role:
        name: "wildfly_install"

  post_tasks:
    - name: "Proceed with yaml setup"
      ansible.builtin.include_role:
        name: "wildfly_systemd"