---
wildfly_user: "{{ override_wildfly_user | default('wildfly') }}"
widfly_group: "{{ override_wildfly_group | default(wildfly_user) }}"
wfly_version_default: 24.0.0.Final
wfly_version: "{{ wildfly_version | default(wfly_version_default) }}"
workdir: /opt/wildfly/
wfly_zipfile: "wildfly-{{ wfly_version }}.zip"
wfly_download_baseurl: 'https://download.jboss.org/wildfly'
wfly_download_url: "{{ wfly_download_baseurl }}/{{ wfly_version }}/{{ wfly_zipfile }}"
wildfly_config_base: "{{ override_wildfly_config_base | default('standalone.xml') }}"
wildfly:
  home: "{{ workdir }}/wildfly-{{ wfly_version }}/"
  config: "{{ wildfly_config_base }}"
  user: "{{ wildfly_user | default('wildfly') }}"
  min_mem: 64m
  max_mem: 512m
  metaspace_size: 96m
