---
wildfly_version: '26.0.0.Final'
wildfly_archive_filename: "wildfly-preview-{{ wildfly_version }}.zip"
wildfly_download_baseurl: 'https://github.com/wildfly/wildfly/releases/download'
wildfly_install_workdir: '/opt/wildfly/'
wildfly_home: "{{ wildfly_install_workdir }}wildfly-preview-{{ wildfly_version }}/"
wildfly_install_download_url: "{{ wildfly_download_baseurl }}/{{ wildfly_version }}/{{ wildfly_archive_filename }}"
wildfly_archive_dir: "{{ wildfly_install_workdir }}"
wildfly_config_base: 'standalone.xml'
wildfly_user: 'wildfly'
wildfly_group: "{{ wildfly_user }}"
jboss_eap_rhn_id: 'none'
wildfly_jvm_memory_min: '64m'
wildfly_jvm_memory_max: '512m'
wildfly_jvm_metaspace_size: '96m'
wildfly_java_package_name: 'java-1.8.0-openjdk'
